### ISSUE TITLE
Kubectl process getting stuck and does not exit 

### ISSUE THREAD

**Issue by SnehaMore20** [redradrat/aws-iam-operator#6]
If we try to delete iamrole which already has a policy attached, the kubectl process gets stuck and does not exit. Had to force exit the command with ctrl+c 

Controller logs shows continuous error:
`ERROR	controllers.Role	unable to delete Role	{"role": "default/role-sample1", "error": "DeleteConflict: Cannot delete entity, must detach all policies first.\n\tstatus code: 409, request id: 52f76e23-fa39-4f23-8584-9ca0e287d389"}`

When we removed policy from role, the role got deleted automatically by the controller.

**Comment by redradrat** [comment]
Kubectl waits for the resource to be gone basically. As the finalizer on the resource is blocking deletion, this is not happening. This is currently how we deal with kubernetes' _Finalizers_.
