### ISSUE TITLE
Add prefix to all the aws resource created by aws-iam-operator

### ISSUE THREAD

**Issue by SnehaMore20** [redradrat/aws-iam-operator#8]
Providing this feature will help in maintaining same resource names at cluster level and have environment specific aws-resource names in AWS account

**Comment by redradrat** [comment]
In order to increase flexibility we can introduce a global `--resource-prefix="string"` option for the controller itself, that would prefix all resources with the given value. Different "scopes" would then require multiple controller deployments with maybe a label selector?

**Comment by redradrat** [comment]
Implemented as of #11
